### PR TITLE
Fix daemon restart after upgrade

### LINKED ISSUE #8: DAEMON_RESTART_AFTER_UPGRADE should only restart when there is an upgrade
With DAEMON_RESTART_AFTER_UPGRADE, the upgrade manager will continue restarting the child process whenever the exit code is 0. It should only restart when there is an actual upgrade. For instance if I call a command other than `start`, like `unsafe-reset-all` that has a 0 exit code, that shouldn't restart. This is because `LaunchProcess` only returns `error`, it should probably return `(err error, doUpgrade bool)` and there's only a restart when `doUpgrade == true`.

### PR DESCRIPTION
**Pull request by charymalloju**
Closes #8

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -19,11 +19,11 @@ func Run(args []string) error {
...
 		return err
 	}
-	err = LaunchProcess(cfg, args, os.Stdout, os.Stderr)
+	doUpgrade, err := LaunchProcess(cfg, args, os.Stdout, os.Stderr)
 
 	// if RestartAfterUpgrade, we launch after a successful upgrade (only condition LaunchProcess returns nil)
-	for cfg.RestartAfterUpgrade && err == nil {
-		err = LaunchProcess(cfg, args, os.Stdout, os.Stderr)
+	for cfg.RestartAfterUpgrade && err == nil && doUpgrade {
+		_, err = LaunchProcess(cfg, args, os.Stdout, os.Stderr)
```
Comment (ethanfrey) [inline main.go]: since this is a loop, we should have `doUpgrade, err = ` here as well, right?

(in the given use case, this probably doesn't matter, but good for correctness in unexpected cases)

File: process.go [hunk 2]
```diff
@@ -12,40 +12,43 @@ import (
...
 // either when it dies, or *after* a successful upgrade.
-func LaunchProcess(cfg *Config, args []string, stdout, stderr io.Writer) error {
+func LaunchProcess(cfg *Config, args []string, stdout, stderr io.Writer) (bool, error) {
+	var doUpgrade bool
 	bin := cfg.CurrentBin()
+
 	err := EnsureBinary(bin)
 	if err != nil {
-		return errors.Wrap(err, "current binary invalid")
+		return doUpgrade, errors.Wrap(err, "current binary invalid")
```
Comment (ethanfrey) [inline process.go]: I find this confuing, as you must scan all the code above this point to understand if it is true or false.
Why not just use a constant everywhere - eg, `return false, errors.Wrap(err, "current binary invalid")`

File: process.go [hunk 3]
```diff
@@ -12,40 +12,43 @@ import (
...
 	// three ways to exit - command ends, find regexp in scanOut, find regexp in scanErr
 	upgradeInfo, err := WaitForUpgradeOrExit(cmd, scanOut, scanErr)
 	if err != nil {
-		return err
+		return doUpgrade, err
 	}
 	if upgradeInfo != nil {
-		return DoUpgrade(cfg, upgradeInfo)
+		doUpgrade = true
+		return doUpgrade, DoUpgrade(cfg, upgradeInfo)
```
Comment (ethanfrey) [inline process.go]: You can simplify this to `return true, DoUpgrade(cfg, upgradeInfo)`

and let the final case remain as `return false, nil`

**Review by ethanfrey — COMMENTED** [review]
Approach is correct. Some code cleanup suggested.

I would ask for a unit test, but since the relevant logic is in `main.go`, I'm not sure if this is practical

File: process.go (hunk 3 above)
Comment (anilcse) [reply process.go]: Yes, that will be straight forward. I will update
