### PR TITLE
Fix create symlinking to genesis

### LINKED ISSUE #9: current should get symlinked to genesis as well
Currently symlinking to `current` only happens for upgrades not genesis, it should happen for both.

### PR DESCRIPTION
**Pull request by charymalloju**
Closes #9

### CODE REVIEW

File: args.go [hunk 1]
```diff
@@ -44,28 +45,85 @@ func (cfg *Config) UpgradeDir(upgradeName string) string {
...
+
+	//Write current binary to file
+	WriteToFile(curBin)
+
 	// and return the binary
-	return filepath.Join(dest, "bin", cfg.Name)
+	return curBin
+}
+
+func WriteToFile(path string) {
```
Comment (ethanfrey) [inline args.go]: I don't understand this function - why the `*.txt` file? We should have a sym link to the other directory.

File: args.go [hunk 2]
```diff
@@ -44,28 +45,85 @@ func (cfg *Config) UpgradeDir(upgradeName string) string {
...
 // CurrentBin is the path to the currently selected binary (genesis if no link is set)
 // This will resolve the symlink to the underlying directory to make it easier to debug
 func (cfg *Config) CurrentBin() string {
 	cur := filepath.Join(cfg.Root(), currentLink)
 	// if nothing here, fallback to genesis
 	info, err := os.Lstat(cur)
 	if err != nil {
-		return cfg.GenesisBin()
+		//Create symbolink to the genesis
+		return cfg.SymLinkToGenesis()
```
Comment (ethanfrey) [inline args.go:67]: Yes, replace `cfg.GenesisBin()` => `cfg.SymlinkToGenesis()` is a good change. 
The parts at the end not really necessary

File: args.go [hunk 3]
```diff
@@ -44,28 +45,85 @@ func (cfg *Config) UpgradeDir(upgradeName string) string {
 	return filepath.Join(cfg.Root(), upgradesDir, safeName)
 }
 
+//Symbolinking to genesis
+func (cfg *Config) SymLinkToGenesis() string  {
```
Comment (ethanfrey) [inline args.go]: Not really sure what this is supposed to do. You can simply take https://github.com/regen-network/cosmosd/blob/master/upgrade.go#L137-L160 and modify it a bit.

Returning `(string, error)` is probably best here, as we may be unable to create the link and must abort with a proper message. This also implies `CurrentBin()` should return `(string, error)` and updates to anything calling it.

**Review by ethanfrey — CHANGES_REQUESTED** [review]
You update the proper entry point, but I am quite confused about your approach to creating the symlink. I referenced existing code that does 90% of what you want.

Also, please start with a unit test - this will improve your development speed as well, a simple test to call `CurrentBin()` with different scenarios and insure the link is created on disk and works properly after load. There are plenty of tests in https://github.com/regen-network/cosmosd/blob/master/upgrade_test.go than can be copied and modified to do this - the test setup is done for you

**Comment by ethanfrey** [comment]
Rebased on master and resolved conflicts

**Review by ethanfrey — COMMENTED** [review]
Nice update. I think this is correct, and I rebased on the other two PRs.

I will do a final review later today or tomorrow early

**Review by ethanfrey — APPROVED** [review]
Added a test case and small fix for how the genesis link is created.
Now it looks good
